# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AddTime.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 130)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(10, 10, 91, 51))
        self.label.setStyleSheet("font: 16pt \"Perpetua\";")
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(80, 90, 231, 31))
        self.pushButton.setStyleSheet("font: 13pt \"Perpetua\";")
        self.pushButton.setObjectName("pushButton")
        self.line_name = QtWidgets.QLineEdit(Dialog)
        self.line_name.setGeometry(QtCore.QRect(110, 20, 271, 31))
        self.line_name.setText("")
        self.line_name.setObjectName("line_name")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Время:"))
        self.pushButton.setText(_translate("Dialog", "Добавить"))
